POST {{base_url}}/auth/login
Content-Type: application/json  

{
 "email":"salman@gmail.com",
 "password":"Salman@123"
}

###
POST {{base_url}}/auth/logout

### 
POST {{base_url}}/auth/register
Content-Type: application/json

{
    "firstName": "salman",
    "lastName": "khan",   
    "email": "saslman@gmail.com",
    "password":"Salman@123",
    "phone": "+919805893577"
}

### confirm email
POST {{base_url}}/auth/confirm-email
Content-Type: application/json

{  
    "jwt":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJUeXBlIjozLCJpYXQiOjE3MTg2NjczMjYsImV4cCI6MTc1MDIwMzMyNn0.fbwmiZeUxL_ghPipvuYq1-oQwrfGv3R5K6o9DsQfiUM"
}


### forgot password otp
POST {{base_url}}/auth/forgot-password
Content-Type: application/json

{  
    "email": "salman@gmail.com"
}

### reset password 
POST {{base_url}}/auth/reset-password
Content-Type: application/json

{  
    "email": "salman@gmail.com",
    "password":"Salman@123",
    "jwt":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJUeXBlIjozLCJpYXQiOjE3MTg2NjczMjYsImV4cCI6MTc1MDIwMzMyNn0.fbwmiZeUxL_ghPipvuYq1-oQwrfGv3R5K6o9DsQfiUM"
}
