POST {{base_url}}/auth/login
Content-Type: application/json  

{
 "email":"salman@gmail.com",
 "password":"Salman@123"
}

###
POST {{base_url}}/auth/logout

###
POST {{base_url}}/auth/register
Content-Type: application/json

{
    "firstName": "salman",
    "lastName": "khan",   
    "email": "salman@gmail.com",
    "password":"Salman@123",
    "phone": "+919805893577"
}

### forgot password otp
POST {{base_url}}/auth/forgot-password-otp
Content-Type: application/json

{  
    "email": "salman@gmail.com"
}
