export enum NotificationType {
  BOOKING_CREATED,
  BOOKING_RECIEVED,
  BOOKING_COMFIRMED,
  BOOKING_CANCLED,
  BOOKING_REJECTED,
  BOOKING_TRIP_STARTED,
  BOOKING_COMPLETE,
  PAYMENT_RECIEVED,
  REFUND_INITIATED,
  REFUND_ISSUED,
}
